### ISSUE TITLE
Bad mount path for file uploads

### ISSUE THREAD

**Issue by moufmouf** [theaentmachine/aent-kubernetes#28]
For a PHP image, if we generate a persistent volume claim for the file uploads, the mountPath option is wrong.

**deployment.yml**
```
volumeMounts:
            1:
              name: apistorageapppublic_data
              mountPath: api/storage/app/public
            2:
              name: apistorageframeworksessions_data
              mountPath: api/storage/framework/sessions
```

The correct generated file should be instead:

```
volumeMounts:
            -
              name: apistorageapppublic_data
              mountPath: /var/www/html/storage/app/public
            -
              name: apistorageframeworksessions_data
              mountPath: /var/www/html/storage/framework/sessions
```
