### ISSUE TITLE
Template substituion fails

### ISSUE THREAD

**Issue by moufmouf** [theaentmachine/aent-kubernetes#29]
On a RANCHER deploy:

```
deploy_test:
  image: 'lwolf/kubectl_deployer:latest'
  stage: deploy
  variables:
    KUBECONFIG: /root/.kube/config
    K8S_DIRNAME: kubernetes-test
  script:
  - 'mkdir ~/.kube'
  - 'echo "$KUBE_CONFIG" > ~/.kube/config'
  - 'kubectl create namespace ${CI_PROJECT_PATH_SLUG}-${CI_COMMIT_REF_SLUG} || true'
  - 'kubectl -n ${CI_PROJECT_PATH_SLUG}-${CI_COMMIT_REF_SLUG} delete all --all'
  - 'cd ${K8S_DIRNAME}'
  - 'for template_file in $(find . -type f -name "*.template"); do sed -e "s/#ENVIRONMENT#/${CI_COMMIT_REF_SLUG}/g"
    $template_file > ${template_file::-9}; done'
  - 'for yml_file in $(find . -type f -name "*.yml" -or -name "*.yaml"); do kubectl
    -n ${CI_PROJECT_PATH_SLUG}-${CI_COMMIT_REF_SLUG} apply -f ${yml_file}; done'
  only:
  - branches
  except:
  - master
```

I get this error:

```
$ for template_file in $(find . -type f -name "*.template"); do sed -e "s/#ENVIRONMENT#/${CI_COMMIT_REF_SLUG}/g" $template_file > ${template_file::-9}; done
/bin/sh: eval: line 80: Illegal number: -9
ERROR: Job failed: exit code 2
```

This is because the `${template_file::-9}` syntax is a bash syntax but the 'lwolf/kubectl_deployer:latest' image is based on Ash.
